### ISSUE TITLE
Issue with package name

### ISSUE THREAD

**Issue by TylerHobanDotCom** [danielgraycode/discord-RPC-Node#1]
The package name is `discord-rpc` which is also the name of a dependency which can break `npm install`.

**Comment by mimimememimi** [comment]
This is pretty simple stuff to fix. Can't you just rename the package such as `discord-rpc-client` or anything similar? Changing the package name would not bump into many issues.

**Comment by TylerHobanDotCom** [comment]
yes obviously you can just rename, it's still an issue. ill close tho
